// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5sbEJYvPD5dnz1G0v4ZTv71VJHxKgRl4',
    appId: '1:432029571062:web:5e9dda7a05d9f6f55759d7',
    messagingSenderId: '432029571062',
    projectId: 'fsms-app-94a63',
    authDomain: 'fsms-app-94a63.firebaseapp.com',
    storageBucket: 'fsms-app-94a63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ2EhvpiHWZDMkTEYMmmvlHR1UO8XuG5k',
    appId: '1:432029571062:ios:0c08a410343bbe285759d7',
    messagingSenderId: '432029571062',
    projectId: 'fsms-app-94a63',
    storageBucket: 'fsms-app-94a63.firebasestorage.app',
    iosBundleId: 'com.example.fsmsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ2EhvpiHWZDMkTEYMmmvlHR1UO8XuG5k',
    appId: '1:432029571062:ios:0c08a410343bbe285759d7',
    messagingSenderId: '432029571062',
    projectId: 'fsms-app-94a63',
    storageBucket: 'fsms-app-94a63.firebasestorage.app',
    iosBundleId: 'com.example.fsmsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5sbEJYvPD5dnz1G0v4ZTv71VJHxKgRl4',
    appId: '1:432029571062:web:bf0b6fd14b7a9d445759d7',
    messagingSenderId: '432029571062',
    projectId: 'fsms-app-94a63',
    authDomain: 'fsms-app-94a63.firebaseapp.com',
    storageBucket: 'fsms-app-94a63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZFOxPqpZ7RU35Kpa_f-T9kKu1LH_nF0',
    appId: '1:432029571062:android:606502b90857480e5759d7',
    messagingSenderId: '432029571062',
    projectId: 'fsms-app-94a63',
    storageBucket: 'fsms-app-94a63.firebasestorage.app',
  );

}