// motivation_vault_screen.dart
import 'package:flutter/material.dart';

class MotivationVaultScreen extends StatelessWidget {
  const MotivationVaultScreen({super.key});

  // 🔥 SINGLE SOURCE OF TRUTH
 static const List<String> quotes = [
"Believe in yourself 💪",
"Success is built daily",
"Discipline beats motivation",
"Dream big. Start now",
"You are stronger than you think",
"Consistency creates success",
"Focus on progress, not perfection",
"Make today count",
"Your future self is watching",
"Never give up 🔥",
"Small steps lead to big results",
"Action cures fear",
"Stay hungry, stay foolish",
"Hard work beats talent",
"Growth begins outside comfort",
"Do it even when you don’t feel like it",
"Be better than yesterday",
"Excuses don’t build dreams",
"Your only limit is you",
"Turn pain into power",
"Done is better than perfect",
"Start where you are",
"Progress over perfection",
"You didn’t come this far to quit",
"One day or day one — you decide",
"Stay focused, stay sharp",
"Your mindset shapes your future",
"Keep showing up",
"Courage over comfort",
"Build habits, not wishes",
"Make discipline your superpower",
"Push yourself gently but daily",
"Failure is feedback",
"Win the morning, win the day",
"Invest in yourself first",
"Success loves preparation",
"Patience builds greatness",
"Keep moving forward",
"You owe it to yourself",
"Strong mind, strong life",
"Do what future you will thank you for",
"Work silently, shine loudly",
"Energy flows where focus goes",
"Master the basics",
"Stay consistent even when bored",
"Dreams demand discipline",
"Fear is temporary, regret lasts",
"Make discomfort your teacher",
"Your effort matters",
"Trust the process",
"Rise above excuses",
"Focus beats motivation",
"Clarity creates power",
"Stay humble, work hard",
"Your path is unique",
"Believe → Act → Achieve",
"Make progress visible",
"Habits shape destiny",
"Momentum beats intensity",
"Greatness is daily practice",
"Success is a marathon",
"Guard your time",
"Protect your energy",
"Be unstoppable",
"Learn, adapt, improve",
"Start before you’re ready",
"Your story isn’t over",
"Stay patient and persistent",
"Growth takes time",
"Be proud of small wins",
"Mindset is everything",
"Stay curious",
"Turn setbacks into comebacks",
"Hard days build strong people",
"Show up for yourself",
"Keep your promises to yourself",
"Confidence comes from action",
"Silence the doubt",
"Choose progress daily",
"Your work will pay off",
"Stay sharp, stay focused",
"Your goals need you",
"Build resilience",
"Success is earned, not given",
"Think long term",
"Stay disciplined",
"Create your own luck",
"Be fearless in pursuit",
"Focus on solutions",
"Keep climbing",
"Make every hour count",
"Choose growth",
"Your potential is huge",
"Take responsibility",
"Stay grounded",
"Push beyond limits",
"Your grind will shine",
"Control what you can",
"Be proud of effort",
"Keep evolving",
"Success starts with belief",
"Stay determined",
"Hard work compounds",
"Be your best investment",
"Progress is power",
"Keep pushing",
"Your journey matters",
"Stay resilient",
"Aim higher",
"Create momentum",
"Be unstoppable today",
"Rise and grind",
"Keep your standards high",
"Focus on becoming",
"Stay mentally tough",
"Make it happen",
"Believe in progress",
"Stay driven",
"Win your battles",
"Consistency wins",
"Dream. Plan. Execute.",
"Build daily discipline",
"Stay motivated by purpose",
"Take bold action",
"Success favors courage",
"Do the work",
"Be relentless",
"Stay committed",
"Your effort defines you",
"Never settle",
"Choose excellence",
"Stay ambitious",
"Push forward always",
"Own your future",
"Work with purpose",
"Stay sharp mentally",
"Think big, act daily",
"Lead yourself first",
"Your grind matters",
"Make today legendary",
"Stay hungry",
"Grow stronger daily",
"Be intentional",
"Create impact",
"Stay focused on goals",
"Push through fatigue",
"Level up daily",
"Build a winning mindset",
"Stay optimistic",
"Keep striving",
"Make sacrifices count",
"Stay fearless",
"Choose action",
"Create success habits",
"Work smart and hard",
"Rise above average",
"Keep improving",
"Stay inspired",
"Build momentum daily",
"Stay unstoppable",
"Be proud of effort",
"Trust your journey",
"Stay powerful",
"Aim for greatness",
"Keep your vision clear",
"Stay focused on why",
"Build inner strength",
"Turn dreams into plans",
"Stay patient but active",
"Make it count",
"Own your decisions",
"Keep faith in yourself",
"Stay consistent always",
"Push past doubt",
"Choose growth daily",
"Make your future proud",
"Keep climbing higher",
"Work with passion",
"Stay focused on success",
"Create positive habits",
"Stay mentally strong",
"Push beyond comfort",
"Keep your fire alive",
"Build your empire",
"Stay bold",
"Think like a winner",
"Stay disciplined daily",
"Turn goals into reality",
"Be proud of progress",
"Stay committed to growth",
"Keep going no matter what",
"Make yourself proud",
"Rise above negativity",
"Stay productive",
"Push toward excellence",
"Keep chasing dreams",
"Stay unstoppable today",
"Build strength daily",
"Stay focused on improvement",
"Turn effort into results",
"Stay energized",
"Work for your future",
"Keep faith alive",
"Stay driven always",
"Make discipline your identity",
"Stay hungry for success",
"Push past limits",
"Stay committed to greatness",
"Keep evolving daily",
"Build success mindset",
"Stay sharp and focused",
"Create your destiny",
"Stay resilient always",
"Work with determination",
"Stay focused on vision",
"Push forward bravely",
"Keep believing",
"Stay courageous",
"Make your mark",
"Stay determined daily",
"Build confidence through action",
"Stay relentless",
"Keep grinding",
"Stay motivated daily",
"Turn obstacles into opportunities",
"Stay ambitious always",
"Work toward mastery",
"Stay positive",
"Build strong habits",
"Keep rising",
"Stay unstoppable forever",
"Make every day productive",
"Stay powerful inside",
"Push toward your best self",
"Stay committed to dreams",
"Keep moving ahead",
"Stay confident",
"Make progress daily",
"Stay fearless in action",
"Keep learning",
"Stay energized for success",
"Build your legacy",
"Stay focused always",
"Turn vision into victory",
"Stay disciplined forever",
"Keep growing stronger",
"Stay hopeful",
"Make success inevitable",
"Stay passionate",
"Push through challenges",
"Stay unstoppable no matter what",
"Build courage daily",
"Stay focused on purpose",
"Make your dreams real",
"Stay resilient through storms",
"Keep winning small battles",
"Stay determined to succeed",
"Make effort your habit",
"Stay focused on greatness",
"Keep pushing boundaries",
"Stay strong mentally",
"Make success your routine",
"Stay bold in pursuit",
"Keep faith in journey",
"Stay powerful every day",
"Push toward excellence always",
"Stay committed to winning",
"Make your effort count",
"Stay consistent forever",
"Keep chasing greatness",
"Stay focused on improvement",
"Build unstoppable confidence",
"Stay disciplined for life",
"Make progress inevitable",
"Stay driven by purpose",
"Keep pushing forward",
"Stay unstoppable in spirit",
"Make each day better",
"Stay resilient and strong",
"Keep striving for more",
"Stay courageous daily",
"Make success your destiny",
"Stay focused and fearless",
"Keep improving forever",
"Stay powerful in mind",
"Make today a victory",
"Stay relentless in pursuit",
"Keep building your dream",
"Stay unstoppable in action",
"Make greatness your goal",
"Stay focused on success",
"Keep growing every day",
"Stay determined to win",
"Make discipline your power",
"Stay committed to excellence",
"Keep pushing limits",
"Stay strong and fearless",
"Make your journey legendary",
"Stay hungry for growth",
"Keep moving upward",
"Stay unstoppable always",
"Make progress your lifestyle",
"Stay bold and confident",
"Keep rising higher",
"Stay focused on becoming",
"Make success your story",
"Stay disciplined and strong",
"Keep pushing toward greatness",
"Stay powerful every moment",
"Make today extraordinary",
"Stay relentless daily",
"Keep working on yourself",
"Stay unstoppable forever 🔥"
];

  // 🔥 SHARED LOGIC
  static int getTodayIndex() {
    final baseDate = DateTime(2024, 1, 1);
    final today = DateTime.now();
    return today.difference(baseDate).inDays % quotes.length;
  }

  static String getTodayQuote() {
    return quotes[getTodayIndex()];
  }

  @override
  Widget build(BuildContext context) {
    final todayIndex = getTodayIndex();
    final todayQuote = getTodayQuote();

    return Scaffold(
      appBar: AppBar(
        title: const Text("Motivation Vault"),
        centerTitle: true,
        backgroundColor: Colors.deepPurple,
      ),
      body: Column(
        children: [
          // 🔥 TODAY CARD
          Container(
            width: double.infinity,
            margin: const EdgeInsets.all(16),
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                colors: [Color(0xFF5A4BE7), Color(0xFF7B61FF)],
              ),
              borderRadius: BorderRadius.circular(20),
            ),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  "Day ${todayIndex + 1} of ${quotes.length}",
                  style: const TextStyle(color: Colors.white70),
                ),
                const SizedBox(height: 8),
                Text(
                  todayQuote,
                  style: const TextStyle(
                    color: Colors.white,
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ],
            ),
          ),

          // 📜 LIST
          Expanded(
            child: ListView.builder(
              padding: const EdgeInsets.all(16),
              itemCount: quotes.length,
              itemBuilder: (context, index) {
                final isToday = index == todayIndex;

                return Container(
                  margin: const EdgeInsets.only(bottom: 12),
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: isToday
                        ? Colors.deepPurple.shade100
                        : Colors.deepPurple.shade50,
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: Text(
                    quotes[index],
                    style: TextStyle(
                      fontWeight:
                          isToday ? FontWeight.bold : FontWeight.normal,
                    ),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}